// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwheIXHlGfin6piwTfQTH36mBTre8yb9k',
    appId: '1:274409886635:web:a10374dccb33450c3978ee',
    messagingSenderId: '274409886635',
    projectId: 'crudoperation-62732',
    authDomain: 'crudoperation-62732.firebaseapp.com',
    storageBucket: 'crudoperation-62732.appspot.com',
    measurementId: 'G-M14QM46736',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp2tNW-Iw1AD86b_sbN_FASEEjZ76Cruo',
    appId: '1:274409886635:android:ce7889d7b86b4eda3978ee',
    messagingSenderId: '274409886635',
    projectId: 'crudoperation-62732',
    storageBucket: 'crudoperation-62732.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_QgQsTpp-FPaa9ztFez1SfnnVPb464Ts',
    appId: '1:274409886635:ios:0c9e8e34c53dfe5f3978ee',
    messagingSenderId: '274409886635',
    projectId: 'crudoperation-62732',
    storageBucket: 'crudoperation-62732.appspot.com',
    iosBundleId: 'com.example.crudoperation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_QgQsTpp-FPaa9ztFez1SfnnVPb464Ts',
    appId: '1:274409886635:ios:0c9e8e34c53dfe5f3978ee',
    messagingSenderId: '274409886635',
    projectId: 'crudoperation-62732',
    storageBucket: 'crudoperation-62732.appspot.com',
    iosBundleId: 'com.example.crudoperation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwheIXHlGfin6piwTfQTH36mBTre8yb9k',
    appId: '1:274409886635:web:6ce5f3f0f7f707c53978ee',
    messagingSenderId: '274409886635',
    projectId: 'crudoperation-62732',
    authDomain: 'crudoperation-62732.firebaseapp.com',
    storageBucket: 'crudoperation-62732.appspot.com',
    measurementId: 'G-LY81TNXDTT',
  );
}
